server:
  port: 9000

spring:
  application:
    name: SpringTesting
  profiles:
#    active: test
    active: default
  # datasource example
  datasource:
    url: jdbc:mysql://localhost:3306/db_temp?useSSL=false&serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update


